### ISSUE TITLE
PowerPoint Plugin

### ISSUE THREAD

**Issue by stefanstranger** [iainbrighton/PScribo#1]
Feature request PowerPoint Plugin. Would be great if there was also a PowerPoint Plugin. 
I've created some PowerShell script that could create PPTs. Check https://www.youtube.com/watch?v=brAqvBJFtRs Will need to search for PowerShell code in my archive to check if this can help create a PPT plugin for PScribo module

**Comment by iainbrighton** [comment]
Hi Stefan,

I'm intrigued with your use case and never intended PScribo to be used to create pptx files. A PowerPoint plugin could be added. My initial thoughts would be on whether it could be easily mapped to the current DSL or would need its own structure/format. Thoughts?

Thanks, Iain
