### ISSUE TITLE
DocumentOption DefaultFont not working

### ISSUE THREAD

**Issue by Tragen** [iainbrighton/PScribo#100]
The DefaultFont in DocumentOption doesn't work.
Currently I use a Style with the Default switch as a workaround.

**Comment by iainbrighton** [comment]
Thanks @Tragen - I think there's some confusion here. That option is not the default font for the document, just the default font(s) used when defining styles. Hopefully, this example will clear things up:
```powershell
$doc = Document Issue100 {
    ## Set the default font(s) for new styles
    DocumentOption -DefaultFont Arial 
    ## Create a new custom style - using the default font(s) if -Font not specified
    Style -Name Custom -Size 16
}
```
To set the default font for the document you should continue to use the `-Default` switch. It's probably "best practice" to just override the default/built-in `Normal` style:
```powershell
$doc = Document Issue100 {
    Style -Name Normal -Size 16 -Font 'Arial','Tahoma'
}
```

**Comment by Tragen** [comment]
Thanks for the clarification. That makes sense.
