### ISSUE TITLE
Feature request: Images in documents

### ISSUE THREAD

**Issue by wiltaylor** [iainbrighton/PScribo#12]
It would be really awesome to be able to have images injected into HTML and word documents (maybe just a url or path in text documents).

The main use case for this would be as follows:
- Inserting graphs into documents.
- Inserting screenshots from automated tests that can show unexpected errors etc.

**Comment by iainbrighton** [comment]
@wiltaylor Yes - this is something that I plan to add, as I could do with be able to add charts to Word/Html documents. Here are some notes (thinking out loud) about what I feel would be needed:

* Supports both file and web URIs
 * Word output should embed the image.
 * Html output should link the image.
 * All other plugins should just provide a link.
* Support specifying image size (height/width)
* Support image alignment
* Support adding borders?

Anything else that you think is needed or is missing?

**Comment by wiltaylor** [comment]
No that sounds perfect :). 

Only thing I can think of with html is have it copy the images into the same directory as the html file so it can easily be turned into an email.

**Comment by matt2005** [comment]
I've started on word image support see #52

**Comment by tpcarman** [comment]
Was this included in release 0.7.19.93?

**Comment by iainbrighton** [comment]
@tpcarman No - not yet. There is a [working implementation](https://github.com/iainbrighton/PScribo/tree/Image) but it currently has no HTML output plugin and is not currently compatible with PS Core on Linux and MacOS. Can you take it for a spin and let me know what does/doesn't work?

**Comment by iainbrighton** [comment]
@tpcarman PowerShell Core support has been added to the Word output in the latest commit to the Image branch - thanks @matt2005 for the contribution! I will hopefully look at adding Html Image output and documentation soon.
