### ISSUE TITLE
New PSScriptAnalyzer rule generates error

### ISSUE THREAD

**Issue by carceneaux** [iainbrighton/PScribo#123]
A couple months ago, the latest version of the [PSSCriptAnalyzer was released](https://github.com/PowerShell/PSScriptAnalyzer/releases). In it, a new rule - [AvoidMultipleTypeAttributes](https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/rules/avoidmultipletypeattributes?view=ps-modules) - was included that is generating an error:

https://ci.appveyor.com/project/iainbrighton/pscribo/builds/45596594

![CleanShot 2022-12-07 at 08 35 35](https://user-images.githubusercontent.com/17179966/206193193-a1c31a2b-b521-42b8-a13d-8a0d8af47744.png)

**Comment by iainbrighton** [comment]
I think this is actually an error with the PSScriptAnalyzer rule with the `[ref]` attribute. We could just skip this test (where applicable) rather than fixing the PSScriptAnalyzer module version?

**Comment by carceneaux** [comment]
Yep, agreed. I'll make the necessary changes to my PR.
