### ISSUE TITLE
Rename GlobalOption to DocumentOption

### ISSUE THREAD

**Issue by iainbrighton** [iainbrighton/PScribo#18]
I think the `GlobalOption` keyword should be renamed to `DocumentOption`. This is better fitting of what it's actually doing: setting the default document options. Thoughts?

**Comment by it-praktyk** [comment]
I agree, but due that can cause incompatibility the major part of version number need to be changed -> [http://semver.org/](http://semver.org/)

**Comment by iainbrighton** [comment]
We could add an alias to ensure backward compatibility?

**Comment by it-praktyk** [comment]
I don't analyze code for that but if is it possible backward compatibility with alias is a good idea.
