### ISSUE TITLE
Skip adding numbers in TOC for a text output

### ISSUE THREAD

**Issue by it-praktyk** [iainbrighton/PScribo#20]
Is it possible to skip adding numbers for items in output to text ?

On the screenshot below you can find doubled numbers for Format-Pester

![2016-07-26 00_15_19-c__users_wojtek_desktop_20160725 txt - notepad](https://cloud.githubusercontent.com/assets/4910261/17119498/96758298-52c6-11e6-92bd-d1460cdeb355.png)

Test based on the content of demo folder in main Format-Pester repo, generated by [dev branch of my fork](https://github.com/it-praktyk/Format-Pester/blob/425e8c92b121f7ac949a0d16fc5bd194bb7705ff/Format-Pester/Public/Format-Pester.ps1).

**Comment by iainbrighton** [comment]
Hi @it-praktyk - that doesn't look right! Are you adding adding/generating numbers on the headings? Does HTML output give you the same output?

**Comment by it-praktyk** [comment]
Yes, I'm adding numbers to TOC in a code.

The screenshot from the HTML

![2016-07-25 23_34_43-20160725](https://cloud.githubusercontent.com/assets/4910261/17152011/4574f030-5376-11e6-8b17-da5bd13d30bd.png)

For text format numbers are added in the lines  97-102 of the file OutText.Internal.ps1

**Comment by iainbrighton** [comment]
@it-praktyk Looking at the code, there is no check for the `-EnableSectionNumbering` option in the OutText.Internal.ps1 file. The HTML equivalent of the missing check can be [found here](https://github.com/iainbrighton/PScribo/blob/dev/Plugins/OutHtml.Internal.ps1#L182).

It's a bug and obviously missing from the tests :-1:. I'll get it fixed unless you've already done it/started it? Thanks for reporting!

**Comment by it-praktyk** [comment]
I didn't start correcting yet. Feel free to do it ;-)

**Comment by iainbrighton** [comment]
@it-praktyk Hopefully the new v0.7.12 release should resolve your issue. Can you test and reopen if it doesn't? Thanks :smiley:

**Comment by it-praktyk** [comment]
Now is fine. Thanks
![pscribo-0 7 12 47-text](https://cloud.githubusercontent.com/assets/4910261/17332700/ebf48f0c-58cf-11e6-84d4-6c4dff9d51c9.jpg)
