### ISSUE TITLE
Export subparts of a document

### ISSUE THREAD

**Issue by iainbrighton** [iainbrighton/PScribo#23]
Created from https://github.com/VirtualEngine/Lability/pull/117:

Is it possible to use PScribo like: Document { Document {} | Export-Document } | Export-Document to export subparts of document?

I've updated Format-Pester to group by Describe/Context and now I would like use text output to open GitHub issue(s) based on subparts.

**Comment by iainbrighton** [comment]
@it-praktyk Yeah - you can't do that :-1:.

However, this might be all you need. Once you have the document object and wish to export some text to log an issue, you could do this:
```powershell
Import-Module -Name PScribo

$document = Document 'Export Subparts' {
    Section 'Section 1' {
        Paragraph 'This is section #1'
    }
    Section 'Section 2' {
        Paragraph 'This is section #2'
        Section 'Section 2.1' {
            Paragraph 'This is section #2.1'
        }
    }
}

$pscribo = Get-Module -Name PScribo

## Each (root) section is stored in the Document.Sections array list. If you can
## locate the relevant section, you can convert it to text like so:
& $pscribo { OutTextSection -Section $document.Sections[0] }

## To get access to section 2.1 you can use this. NOTE: the section is the 2nd
## element as the Paragraph is the first entry in the Sections[] collection.
& $pscribo { OutTextSection -Section $document.Sections[1].Sections[1] }
```
Each (nested) `Sections` is just an array of the components in the document. You can explore the `$document [PSCustomObject]` :wink:.

Does this work for you?

**Comment by it-praktyk** [comment]
@iainbrighton , thank you for explanation,

I'll try implement exporting sub-parts of documents in [Format-Pester](https://github.com/equelin/Format-Pester) soon and based on that files I'll try open issue to missed helps in [Lability](https://github.com/VirtualEngine/Lability).

What do you think about that idea?

CC: @equelin

**Comment by iainbrighton** [comment]
@it-praktyk @equelin Did this solution work out for you?

**Comment by it-praktyk** [comment]
I think that will be OK. I didn't have to fully test it yet.

**Comment by iainbrighton** [comment]
Closing out. Please reopen if you think this issue still needs addressing.
