### ISSUE TITLE
Implement the -PassThru parameters for OutHtml, OutText, Out - an enhancement proposal

### ISSUE THREAD

**Issue by it-praktyk** [iainbrighton/PScribo#25]
Currently if the files are written to disk objects what contain references to the new created files are returned. 

The command used for that is  

``` powershell
Write-Output 
```

in the files/lines like below

https://github.com/iainbrighton/PScribo/blob/dev/Src/Plugins/OutHtml.ps1#L74

https://github.com/iainbrighton/PScribo/blob/dev/Src/Plugins/OutText.ps1#L67

https://github.com/iainbrighton/PScribo/blob/dev/Src/Plugins/OutWord.ps1#L133

My proposal is to implement the PassThru parameter what can be used if that kind of reference object need to be returned. If not any output will not be returned.

**Comment by iainbrighton** [comment]
@it-praktyk Sounds OK to me 👍

**Comment by it-praktyk** [comment]
I'll try implement it.
