### ISSUE TITLE
Ability to have split cells within a table row?

### ISSUE THREAD

**Issue by kilasuit** [iainbrighton/PScribo#27]
Is it possible to have a table row where you have 1 or more cells split as it would be possible to do within word like below?

![splitcells](https://cloud.githubusercontent.com/assets/6355225/18587581/aeeca478-7c1a-11e6-96ab-83a92dde824e.PNG)

**Comment by iainbrighton** [comment]
Not currently. I'm not sure how we could go about implementing this efficiently - both in the DSL and with text output. Word and Html output should be "easier" as they natively support this.

The text-based output currently relies on PowerShell's Format-Table functionality. Implementing column and row spanning would mean having to implement this ourselves for text-based output.

**Comment by iainbrighton** [comment]
@kilasuit I can't see a way of doing this without making things really complicated in the DSL and the plugin output. I suggest you resort to using either the Word COM object or the OpenXml libraries to achieve this 😭.

**Comment by PrzemyslawKlys** [comment]
You can do this with [PSWriteWord](https://github.com/EvotecIT/PSWriteWord). No need to resort to Word COM.
