### ISSUE TITLE
Create a release?

### ISSUE THREAD

**Issue by lboening** [iainbrighton/PScribo#28]
I used PScribo on a Windows 7 machine, and it worked well!

I have many machines at my disposal. My primary workstation is a Windows 7 box. I have added many things over the years, including preview releases of Powershell versions.

I have an earlier version of Powershell 5 from early 2015, still installed, somehow. Due to this,  I am unable to use Find-Package -name Pscribo, or Save-Module. It's just too much work at this juncture to rebuild my machine.

An easy shortcut for me is a zip package. I know how to manually install modules. Is there a chance you could create a release.zip? I would be most happy if you did.

**Comment by iainbrighton** [comment]
Hi @lboening,

Whilst this isn't proper GitHub "release" you can download the latest public release Zip from these locations:

https://github.com/iainbrighton/PScribo/archive/master.zip
https://www.powershellgallery.com/api/v2/package/PScribo

Or if you want the latest __development__ release:
https://github.com/iainbrighton/PScribo/archive/dev.zip

__NOTE: You will need to rename the extracted folder to__ `PScribo`. Does this work for you?

**Comment by iainbrighton** [comment]
Closing out. Please reopen if you think this issue still needs addressing.
