### ISSUE TITLE
Indent HTML Table of Content

### ISSUE THREAD

**Issue by Stephanevg** [iainbrighton/PScribo#33]
Hi Iain, what's up?

I was hoping that you (or anybody else) could help me out on this one. I have quite a dense report, whit several sections that contains several tables etc...

The table of content feature is really great, but I think it laks some visbility. We cannot see the different sections that were originally created in the PScribo document. 

To try to make this more clear, I made a screen shot of how it currently looks like, and added in Green the main section (which is basically a Severname) and in red, the parts that are actually 'in' that section, making it a subpart of that section. 

![image](https://cloud.githubusercontent.com/assets/6302961/23211370/21c9a41e-f902-11e6-91af-b65f2ba4d9ca.png)

Is it possible add some styling to the TOC? I would be happy with an indentation. (or should I tweek something in Document / Section directly?)

Thanks in advance!

*Edit*: Another thing that would be nice as well, is to have the possibility to **only** update add the section titles (so in my case - the computerNames) in the table of content. Any advice on how I could also achieve that?

**Comment by Stephanevg** [comment]
Well, I answered my first question already: 
--> I was simply missing the fact that I needed to put the content in a sub section (so, I have now a section for my server Name, and then the section with my tests).

**Comment by iainbrighton** [comment]
Hi @Stephanevg - 'grats on the new job 😉! Are you all sorted or do you need anything else fixing?!
