### ISSUE TITLE
Proposed enhancement - check for invalid characters in path

### ISSUE THREAD

**Issue by it-praktyk** [iainbrighton/PScribo#38]
I've wrote a module [New-OutputObject](https://github.com/it-praktyk/new-outputobject) what is published to the PowerShell Gallery too - [link](https://www.powershellgallery.com/packages/New-OutputObject).

As the part of that module I'wrote the function Test-CharsInPath what can be used to parse provided names of files for exported documents (the parameter '-Path' in the function Export-Document) for incorrect chars.

The quote from [Test-CharsInPath](https://github.com/it-praktyk/New-OutputObject/blob/master/Private/Test-CharsInPath.ps1) help is below.

```
    .DESCRIPTION
    PowerShell function intended to verify if in the string what is the path to file or folder are incorrect chars.
    Exit codes
    - 0 - everything OK
    - 1 - nothing to check
    - 2 - an incorrect char found in the path part
    - 3 - an incorrect char found in the file name part
    - 4 - incorrect chars found in the path part and in the file name part
```

What do you think about
- incorporate the function Test-CharsInPath to the PScribo module?
- add the new-OutputObject module as optional addition to the PScribo module and a ParameterSet in the Export-Document function?

I see that in [about_ToDo](https://github.com/iainbrighton/PScribo/blob/dev/en-US/about_ToDo.txt) that kind of plan for Output/Plugins.

**Comment by iainbrighton** [comment]
@it-praktyk Checking that the document name is also a valid filename is very worthwhile. If you already have a function that can be used that you're happy to share - I'm all for it 😉. I don't see a need to bundle the whole New-OutputObject module at present?

**Comment by it-praktyk** [comment]
OK, so I'll prepare a pull request . Probably, initially, I'll add names checking only and maybe I'll mention about possibility to extend names preparing in README (?).

**Comment by it-praktyk** [comment]
Does the best place to check the Name of document for unsupported chars is the begin section in the Document function?

**Comment by iainbrighton** [comment]
@it-praktyk Yes - in the `New-PScriboDocument` method. As document name is used for the output filename, if it's invalid we should error when creating the document/object. _Note: thinking ahead we might want to make sure that we cover off invalid Linux characters too?_

**Comment by it-praktyk** [comment]
Today I did first tests the New-OutputObject module on Linux - the module in the current version is not compatible with Linux. I'll try resolve it soon.

**Comment by iainbrighton** [comment]
@it-praktyk Your `New-OutputObject` module implementation is not compatible on Linux? I have dome some initial testing and all unit tests are passing for PScribo Core PowerShell 6 Beta 1 and Beta 2 😃.

**Comment by it-praktyk** [comment]
For the function Test-CharsInPath [I stuck now](https://social.technet.microsoft.com/Forums/windowsserver/en-US/f392aef2-60be-4bc3-83ab-8a09c4d84a5d/powershell-core-how-create-weird-string-with-null-inside?forum=winserverpowershell).

**Comment by it-praktyk** [comment]
@iainbrighton , my New-OutputObject module is compatible with Linux - tested on PowerShell Core v6.0.0-beta4 - the function Test-CharsInPath (what is the subject of #45) too. 
On next week I'll try find someone who will test in on MacOS and test it on Windows Server Nano.
