### ISSUE TITLE
Possible issue for UICulture different than en-US - lack of fallback for Import-LocalizedData

### ISSUE THREAD

**Issue by it-praktyk** [iainbrighton/PScribo#40]
Due to lack of fallback to en-US translation for UICulture different than en-US PScribo probably fails.

Line of code need to be extended : https://github.com/iainbrighton/PScribo/blob/05be8f45674dd69e51a38a0df0d2e0a91479534d/PScribo.psm1#L2

I'll test it soon and if when I'll confirm than fix - in a way like [here](https://github.com/pester/Pester/pull/711/files).

**Comment by iainbrighton** [comment]
@it-praktyk Yes - that would be great. I think the DSC resources so something similar as well.

**Comment by it-praktyk** [comment]
The mentioned previously fix 6b3d73fff6cd3494b872473dd1478f80e8ead95d didn't resolve it.

**Comment by iainbrighton** [comment]
@it-praktyk Looks like you spotted this long ago so apologies for not picking up on it sooner 😢. Version 0.7.17 should fix this? If not, please reopen the issue.
