### ISSUE TITLE
[Question]How can I center a text in a header of table?

### ISSUE THREAD

**Issue by it-praktyk** [iainbrighton/PScribo#47]
I would like center a text in a table header.

The currently my table looks like below
![summary_table](https://cloud.githubusercontent.com/assets/4910261/26765721/4d8ad868-4982-11e7-89c6-447d732cbf2e.jpg)

The best answer for me (#lazymodeon) will be based on the code https://github.com/it-praktyk/Format-Pester/blob/devel/Format-Pester/Public/Format-Pester.ps1#L342-L373 .

Thank you.

**Comment by iainbrighton** [comment]
Hi @it-praktyk , you should be able to override the table header style. If you want to override the defaults. The defaults are set [here](https://github.com/iainbrighton/PScribo/blob/dev/Src/Private/Document.Internal.ps1#L57-L59) when the document is initialised. You should be able to do this:
```powershell
Document TableHeadingExample {
    
    ## Example table
    $summaryTable = [Ordered] @{
        'Total Tests' = 43;
        'Passed Tests' = 14;
        'Failed Tests' = 11;
    }

    ## Override the built-in styles so they are centered
    Style -Name TableDefaultHeading -Size 11 -Color fff -Bold -BackgroundColor 4472c4 -Align Center
    Style -Name TableDefaultRow -Size 11 -Align Center

    Table -Hashtable $summaryTable

} | Export-Document -Format Html -PassThru | Invoke-Item
```
Hopefully that helps?!

**Comment by it-praktyk** [comment]
Thank you.
