### ISSUE TITLE
Page orientation landscape

### ISSUE THREAD

**Issue by irwins** [iainbrighton/PScribo#5]
Having landscape as page orientation would be nice! ;-)

**Comment by simonbyles** [comment]
This would be incredibly useful. I'm using PScribo for tabular reports so portrait orientation can be restrictive.

**Comment by iainbrighton** [comment]
@irwins @simonbyles There is now a `GlobalOption -Orientation Landscape` option. Version 0.7.8 has been pushed to the PowerShell Gallery! Enjoy :smiley:

**Comment by simonbyles** [comment]
Thanks. The new `Landscape` works perfectly and makes my report looks much better.

There is one minor issue in the new version: the portrait option has been misspelt as `Potrait`.

**Comment by iainbrighton** [comment]
DOH. Genius! Good job it's the default ;). Thanks for the heads-up, I'll get it fixed.

**Comment by iainbrighton** [comment]
@simonbyles @irwins I've updated the dev branch with the fix. I won't push this to master/gallery until there are more commits (or unless someone shouts otherwise!).

**Comment by simonbyles** [comment]
Thanks

**Comment by michaeltlombardi** [comment]
@iainbrighton: Since you're following SemVer anyway, I don't see any reason *not* to move forward and release 0.7.9 with this patch.
