### ISSUE TITLE
Compatibility of tests with PowerShell Core on Linux

### ISSUE THREAD

**Issue by it-praktyk** [iainbrighton/PScribo#54]
Recently I updated my PowerShell module [New-OutputObject](https://github.com/it-praktyk/New-OutputObject) to be compatible with PowerShell Core on Linux and MacOS.

The function [Test-CharsInPath](https://github.com/it-praktyk/New-OutputObject/blob/master/Private/Test-CharsInPath.ps1) is part of #53 . But I run all PScribo tests on Linux too.

I see at least two types of tests failures

Case 1 - usage of Get-Service as a source of content for tests.

```
Describing Style\Set-PScriboStyle
   Context By Row.
    [-] sets row style by reference. 146ms
      The term 'Get-Service' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
      at line: 178 in /home/<USERNAME>/Downloads/PScribo/Tests/Unit/Style.Tests.ps1
```

Case 2 - EOL char(s) are different in Windows and Linux

```
Describing OutText.Internal\OutTextBlankLine
 [-] Defaults to a single blank line. 120ms
   Expected string length 2 but was 1. Strings differ at index 0.
   Expected: {\r\n}
   But was:  {\n}
   -----------^
   at line: 82 in /home/wojtek/Downloads/PScribo/Tests/Plugins/OutText.Tests.ps1
   82:             $l | Should Be "`r`n";
 [-] Creates 3 blank lines. 25ms
   Expected string length 6 but was 3. Strings differ at index 0.
   Expected: {\r\n\r\n\r\n}
   But was:  {\n\n\n}
```

Are you interested to make PScribo tests compatible with PowerShell Core on different platforms than Linux?

**Comment by iainbrighton** [comment]
I guess the tests could be updated to use the `[System.Environment]::NewLine` enum. Presumably this just returns `\n` in .NET Core on Linux? As for the services, they could be changed to use Get-Process instead?

**Comment by it-praktyk** [comment]
@iainbrighton, I work now to achieve compatibility of Pester with PSCore - https://github.com/pester/Pester/issues/639. After that, I can return to this case too.

**Comment by it-praktyk** [comment]
@iainbrighton, please reopen it. Thank you.

**Comment by iainbrighton** [comment]
@it-praktyk Hopefully all the tests should now pass on Linux. Can you test and confirm? Thanks, Iain

**Comment by it-praktyk** [comment]
I see a long list of failed tests, e.g.

```
Executing script /home/<folder_name>/PScribo/Tests/Plugins/Text/Out-TextBlankLine.Tests.ps1

  Describing Plugins\Text\Out-TextBlankLine
    [-] Error occurred in Describe block 0ms
      PropertyNotFoundException: The property 'TotalProcessingTime' cannot be found on this object. Verify that the property exists.
      at Document<Process>, <No file>: line 84
      at <ScriptBlock>, /home/<folder_name>/PScribo/Tests/Plugins/Text/Out-TextBlankLine.Tests.ps1: line 12
      at DescribeImpl, /home/<user_name>/.local/share/powershell/Modules/Pester/4.10.1/Functions/Describe.ps1: line 213
```

About a week ago I've tested the PScribo and tests passed then. Today, I've updated PSCore to 7.0.0 GA.

**Comment by iainbrighton** [comment]
Ah - that's my mistake - I missed committing one file 😭, Hopefully, it'll be OK now...

**Comment by it-praktyk** [comment]
Good job!

```
Tests Passed: 1080, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0 
```

**Comment by iainbrighton** [comment]
Thanks for your help/assist!

**Comment by it-praktyk** [comment]
Can you consider releasing the current version to the PowerShell Gallery too?

**Comment by iainbrighton** [comment]
Hi Wojciech - I'll release it soon. I'd like to get some feedback from @tpcarman that I haven't broken anything too badly with all the code refactoring first!

**Comment by tpcarman** [comment]
My quick testing of the `dev` branch on PS 5.1, I get the following error with Word output `Exception calling "Save" with "1" argument(s): "Unable to determine the identity of domain."`. Other outputs appear to work OK. I will investigate further to see if I can isolate the issue.

**Comment by iainbrighton** [comment]
Isn’t that error due to the size of the resulting .docx file being bigger than x? I don’t think the latest version should be generating significantly different document sizes to previous versions (not that I’ve checked)..

**Comment by tpcarman** [comment]
I'm still testing this, however using the exact same environment and parameters, I have no issues with 0.7.26, but get the error using the `dev` branch.
