### ISSUE TITLE
The property 'ClassId' cannot be found on this object.

### ISSUE THREAD

**Issue by jbruett** [iainbrighton/PScribo#58]
Running PScribo 0.7.17.75

I get this while rendering a document.  There doesn't seem to be any direct effect from the error, the document builds as expected.
```
The property 'ClassId' cannot be found on this object. Verify that the property exists.
At line:247 char:17
+ ...             [ref] $null = $tocBuilder.AppendFormat('<h1 class="{0}">{ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict
```

**Comment by iainbrighton** [comment]
@jbruett Thanks for reporting! As @it-praktyk points out, this is known issue. You can download the dev branch or wait until this is published to gallery (hopefully by tomorrow).

**Comment by jbruett** [comment]
Sounds good, I'll wait for the new release and close once confirmed.

**Comment by iainbrighton** [comment]
@jbruett Sorry - v0.7.18.87 was published to the gallery on 2017-09-07, Hopefully this is now resolved?

**Comment by jbruett** [comment]
I can build HTML docs without issue in 0.7.18.87 so I'll assume so
