### ISSUE TITLE
Word Headings 4/5 not outputing correctly

### ISSUE THREAD

**Issue by jbruett** [iainbrighton/PScribo#59]
Version 0.7.18.87

```
$doc = document -name 'testdoc' {
    TOC -Name 'contents'
    section -name 'heading1' -style Heading1 {
        section -name 'heading2' -style Heading2 {
            section -name 'heading3' -style Heading3 {
                section -name 'heading4' -style Heading4 {
                    section -name 'heading5' -style Heading5 {}
            }
        }
    }
}

$doc | export-document -format word -path c:\users\jbruett\desktop\ 
```
produces the output in this file:
[testdoc.docx](https://github.com/iainbrighton/PScribo/files/1385559/testdoc.docx)

HTML formatting is fine.

**Comment by iainbrighton** [comment]
Yeah - there are only 3 styles defined in the [default document](https://github.com/iainbrighton/PScribo/blob/dev/Src/Private/Document.Internal.ps1#L63-L65). I'll need to add `Heading4` and `Heading5` styles.

**Comment by iainbrighton** [comment]
@jbruett thanks for your contribution 😃.
