### ISSUE TITLE
HTML/CSS not working as expected on some non-english cultures

### ISSUE THREAD

**Issue by llstrk** [iainbrighton/PScribo#6]
HTML/CSS requires that decimals be specified with a period ('.'), but some cultures like danish (da-DK) uses a comma (',').

![image](https://cloud.githubusercontent.com/assets/5097150/16083835/ca69bf44-3316-11e6-8d57-bce8ca4e8f12.png)

![image](https://cloud.githubusercontent.com/assets/5097150/16083764/7f202bfe-3316-11e6-8d26-2d04f1d2399d.png)

**Comment by iainbrighton** [comment]
@llstrk Ahh - the joys of localisation/localization 😛. I'll look into getting this fixed and pushed. Thanks for reporting.
