### ISSUE TITLE
Gallery deployment question

### ISSUE THREAD

**Issue by jbruett** [iainbrighton/PScribo#61]
Iain, 

Which branch are you deploying to the gallery from?  I see a lot of the most recent requests merged to dev but not to master.  My PR (#60) don't show up in 0.7.18.87 from the gallery (installed today).

Thanks,

JB

**Comment by iainbrighton** [comment]
Hi @jbruett - it's the master branch that is published to the gallery. Your change is still in the [Unreleased Section](https://github.com/iainbrighton/PScribo#unreleased) of the readme. I'm happy to publish a new version that includes your changes if you want me to?

**Comment by jbruett** [comment]
Iain, that would be great, as I believe that the other fix I've been
waiting for is there as well!

**Comment by iainbrighton** [comment]
@jbruett New version published in the gallery 😉.

```powershell
C:\....\Modules\PScribo [dev ≡]> Find-Module -Name PScribo

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
0.7.19.93  PScribo                             PSGallery            PScribo documentation Powershell module/framework.
```

**Comment by jbruett** [comment]
Thanks Iain.
