### ISSUE TITLE
Limited TOC in Word Docs

### ISSUE THREAD

**Issue by jbruett** [iainbrighton/PScribo#62]
I generated the same document in all four primary output types (html, text, word, xml).  In word, i'm only seeing the first three levels of the TOC, in all other formats i see 6 levels of TOC as expected.  Is the module purposely limiting the Word TOC to 3 levels?

**Comment by iainbrighton** [comment]
@jbruett No artificial limit imposed that I'm aware of, so it is probably the default Word TOC implementation. We'd need to look at changing that in the underlying XML 😟.

**Comment by iainbrighton** [comment]
@jbruett This should be fixed in the latest dev branch. All HeadingX sections should now be displayed, mirroring the other output formats. Thanks for your patience 😉

**Comment by iainbrighton** [comment]
Available in the 0.8.0 release
