### ISSUE TITLE
Trailing spaces are added to text files

### ISSUE THREAD

**Issue by it-praktyk** [iainbrighton/PScribo#67]
I'm not sure is it by design - I didn't check yet - but I see that PScribo v0.7.19 adds trailing spaces in text files.

![2017-11-26 13_11_36-20171125b txt - untitled workspace - visual studio code](https://user-images.githubusercontent.com/4910261/33239870-b858d2fa-d2ab-11e7-87e3-77b76520b4f4.jpg)

**Comment by iainbrighton** [comment]
Hi @it-praktyk I think that it's `Format-Table` that's appending those spaces. PScribo doesn't include its own table formatter for text output..

**Comment by it-praktyk** [comment]
It looks like will be disabled soon https://github.com/PowerShell/PowerShell/pull/5568.
