### ISSUE TITLE
Paragraph -NoNewLine parameter not working

### ISSUE THREAD

**Issue by tpcarman** [iainbrighton/PScribo#75]
When using `Paragraph -NoNewLine`, text is still moved to a new line

```
$Username = $env:USERNAME
$Date = Get-Date -Format D
Document NoNewLine {
    Paragraph "Username: "
    Paragraph $Username -NoNewLine
    Paragraph "Date: "
    Paragraph $Date -NoNewLine
} | Export-Document -Format Word -Path $env:TEMP -Verbose -PassThru | Invoke-Item
```

**Comment by iainbrighton** [comment]
I think I've got to the bottom of this and the solution is not easy. Plain text output is not affected, but HTML output suffers the same fate. Here's a summary:

* In the Office Open XML document a paragraph can have multiple runs
* When we create the Word document, we create a single run inside a paragraph, overly simplified example:
  * `<p><r>My paragraph text</r></p>`
* To append text to a paragraph we would have to add a "run" to the existing paragraph
* Each paragraph is executed in its own scope so the previous context no longer exists 😢.

A solution to this is to add another parameter set to the `Paragraph` function to accept a script block for each "run":

```powershell
Document ParagraphRuns {
    Paragraph {
        Run "This is the first part of a paragraph"
        Run "This will append the second part of a paragraph"
    }
}
```

Would this proposal work? This won't break existing functionality, but would probably require dropping (or deprecating) the `-NoNewLine` parameter on the `Paragraph` function.

_Note: I don't think that `Run` would be a good choice of function name, but would like some suggestions!_

**Comment by iainbrighton** [comment]
Not that it helps, but it seems I did know about this already 😊.

![image](https://user-images.githubusercontent.com/7023258/38978496-801740be-43af-11e8-84a3-15c2e7d6814a.png)

**Comment by iainbrighton** [comment]
@tpcarman This functionality is now available in the dev branch if you want to take it for a spin. You will need to use the new `Paragraph { }` implementation for it to work (the old implementation will remain for compatibility and ease of use). See `Example38.ps1` for more details.
