### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by itamartz** [iainbrighton/PScribo#79]
Can we add image to word,  html?

**Comment by iainbrighton** [comment]
Hi @itamartz - there is a [development branch](https://github.com/iainbrighton/PScribo/tree/Image) with Word support that has recently been updated. Hopefully Html support will be added soon, but it is tracked in issue #12.

**Comment by itamartz** [comment]
Great 10x.
Where can I find the document on XML that build the Word?
I want to help but I don't know the XML structure you build on.

Do you have a support for Heder and footer?

BR,
Itamar

**Comment by iainbrighton** [comment]
Are you really sure you want to look at the Office Open XML documentation? Working with XML is horrible! 

You can find the official documentation here: http://www.ecma-international.org/publications/standards/Ecma-376.htm. Lighter/friendly documentation is here: http://officeopenxml.com/WPheaders.php

**Comment by itamartz** [comment]
Thnx.
Do you have support for table rotation?
Psobject pipe to table and create the props as first column?
It's can help to create services documentation,  for Ad,  Exchange etc…

**Comment by itamartz** [comment]
hi,
Can you assist?

I have a section in my code and it creates the number before the Name in
the TOC and in the Section

you can see my script below and you can see my result
how I can remove the number in the TOC and in the section?
[image: image.png]

tnx
Itamar

**Comment by iainbrighton** [comment]
Hi @itamartz - I can't see the image? Are you saying you are getting duplicate numbers in the TOC and section headers?

**Comment by itamartz** [comment]
Hi,
Tnx you for your reply I figure it out.
I have EnableSectionNumbering in my  'DocumentOption'

tnx
Itamar

**Comment by iainbrighton** [comment]
Excellent. Thanks for the update.
