### ISSUE TITLE
Feature Request: Set page orientation per section

### ISSUE THREAD

**Issue by tpcarman** [iainbrighton/PScribo#81]
Feature request to set page orientation per section.

In some instances tables are too wide for portrait page orientation and have too many entries for a List Table. 

It would be great to be able to set a global page orientation, yet still be able to override and set page orientation per section.

**Comment by iainbrighton** [comment]
I've been thinking about this and we can add an `-Orientation` parameter to the `Section` keyword. Obviously, Word output is fairly straightforward, but Html not so. How would you like to see Html output handled? Should there be an implicit `PageBreak` for every `Section` or just where the orientation is changed?

**Comment by tpcarman** [comment]
I think just where the orientation is changed. You can then always add a PageBreak if required elsewhere for Sections, which I do now. For my summary reports I do have the PageBreak for each main section, whereas for detailed reports I do.
