### ISSUE TITLE
Feature Request: To add HBA/NIC Drivers, Firmware, Version etc.

### ISSUE THREAD

**Issue by vtrimi** [iainbrighton/PScribo#84]
**Feature request** to add the HBA/NIC Drivers, Firmware, Version on to the script.

.HBA-Model (16GB FC to PCI-Express-HBA )
.HBA-Device (vmhba)
.HBA-Driver (lpfcxxx)
.HBA-Firmware-Version
.HBA-WWPN
.VendorName: MassStorageController
.vid / did / svid / ssid

.NIC-Model (10GB )
.NIC-Device (vmnic)
.NIC-Driver
.NIC-Firmware-Version
.DeviceClass: NetworkController
.vid / did / svid / ssid

**Comment by tpcarman** [comment]
Wrong GitHub page. You will want to add that feature request over here https://github.com/tpcarman/As-Built-Report/issues
