### ISSUE TITLE
Add Image as Base64

### ISSUE THREAD

**Issue by itamartz** [iainbrighton/PScribo#86]
I saw in the about_plugin that Image is supported in Base64String.
Can you share an Example on how to add Image to a document?

Tnx

Itamar

**Comment by mc1903** [comment]
@iainbrighton An example would be really helpful if you have time. Cheers. M

**Comment by iainbrighton** [comment]
@itamartz @mc1903 I have now published the image support to the dev branch and see the [example here](https://github.com/iainbrighton/PScribo/blob/dev/Examples/Example31.ps1). Feel free to download the dev version and have a play (it's not yet in the published module/master branch)

**Comment by itamartz** [comment]
Hi,
I just try your Example 31 And I got this error:

[image: image.png]

Clean VM With OUT Word Install on the Machine.
I got this error also when I try Html as Format.

Br,
Itamar

**Comment by itamartz** [comment]
I get the error But On the desktop I can see the files.
If I open I can see your Soccer and the Links.

**Comment by iainbrighton** [comment]
@itamartz I can't see what error you are getting. Can you post the error and what Windows/PowerShell versions you are using?

**Comment by itamartz** [comment]
Can you supply your email I Will send you the Screen Shoot?

Win 10 1709 Build 16299.15

This is the Text for the Error - Export from Snagit

PS C:\Windows\system32>
C:\Program Files\WindowsPowerShell\Modules\PScribo\Examples\Example31.ps!
At line:190 char:35
+ if ($null -ne $memoryStream) { îmenioryStreain.Clos ...
+ Categorylnfo : InvalidOperation: (meraoryStrean:String) [J,
Runtîmetxception
+ FullyQualifiedErrorld : VariablelsUndefined
The variable '$contentStream' cannot be retrieved because it has not been
set.
At line:191 char:35
if ($null -ne îcontentStreani) { $contentStreani.Cl ...

**Comment by iainbrighton** [comment]
No problem - Iainbrighton(at)hotmail(dot)com

**Comment by iainbrighton** [comment]
@itamartz Strange - This is on a fresh Windows 1709 build, downloaded dev branch:

```powershell
PS C:\Users\Iain\Documents\WindowsPowerShell\Modules\PScribo> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.1004
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.1004
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

PS C:\Users\Iain\Documents\WindowsPowerShell\Modules\PScribo> .\Examples\Example31.ps1 -PassThru

    Directory: C:\Users\Iain\Desktop


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       02/05/2019     14:51         114821 PScribo Example 31.docx

PS C:\Users\Iain\Documents\WindowsPowerShell\Modules\PScribo>
```
It is patched, but I will try an unpatched 1709 build and see what happens..

**Comment by itamartz** [comment]
I run the Example from the ISE.

**Comment by iainbrighton** [comment]
Wierd. Works in a stock 1709 build in the ISE too:

![image](https://user-images.githubusercontent.com/7023258/57123606-4dc98180-6d7a-11e9-9e64-ebca1857ef45.png)

**Comment by itamartz** [comment]
From ise open the example file then run it.

**Comment by iainbrighton** [comment]
Hi @itamartz are you still struggling with this? I can open the file and run it successfully from the ISE on Win10 1909 x64 too

**Comment by itamartz** [comment]
I not try,  I will try next week if I have times.
Tnx

**Comment by iainbrighton** [comment]
OK. Please feel free to reopen the issue if you still have problems (v0.7.26 has been published to the PSGallery)
