### ISSUE TITLE
Feature Request: Word table caption numbering

### ISSUE THREAD

**Issue by tpcarman** [iainbrighton/PScribo#88]
Add support for table caption numbering and 'Table of Tables'

| Hostname | MyPC |
| ----------- | ------- |
| IP Address | 192.168.1.10 |

_Table 1: PC Information_

**Comment by iainbrighton** [comment]
@tpcarman This functionality is now available in the dev branch. Can you test and let me know whether it works? Thanks, Iain

**Comment by iainbrighton** [comment]
Available in the 0.8.0 release
